apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- rbac.yaml
namespace: etcd
commonLabels:
  kustomize.component: etcd-operator
images:
  - name: quay.io/coreos/etcd-operator
    newName: quay.io/coreos/etcd-operator
    newTag: v0.9.4
